version: "3"
services:
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=scrapping
      ports:
         - "5432:5432"